name: Build

on: push

jobs:
  build:
    name: Build
    uses: Kotatsu-RTM/.github/.github/workflows/rtmpack_build.yml@master
    with:
      Publishing: true
    secrets:
      RepositoryUsername: ${{ secrets.SIRO256_NEXUS_USER }}
      RepositoryPassword: ${{ secrets.SIRO256_NEXUS_PASSWORD }}
      SigningKeyId: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY_ID }}
      SigningKey: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY }}
      SigningKeyPassword: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY_PASSWORD }}
